README.md, pkgs/default.nix, pkgs/osu-stable/default.nix, pkgs/rocket-league/default.nix, pkgs/technic-launcher/default.nix
Rocket League from Epic Games Store, managed with `legendary-gl`, and Technic Launcher.
=> Add rocket-league and technic-launcher

README.md, pkgs/default.nix, pkgs/osu-lazer-bin/default.nix
`osu-lazer` but extracted from the official AppImage releases to preserve multiplayer support :D
=> osu-lazer-bin: init at 2021.1225.0

flake.lock, pkgs/default.nix, pkgs/osu-lazer-bin/default.nix, pkgs/osu-stable/default.nix, pkgs/rocket-league/default.nix, pkgs/technic-launcher/default.nix, pkgs/wine/default.nix, pkgs/wine/supportFlags.nix
Updated Nixpkgs in order to fix osu!lazer, but had to update everything at once.
=> Update wine derivation, fix `makeDesktopItem` calls

pkgs/wine/default.nix
Didn't test, hoping that CI is happy.
=> wine-tkg: 7.8 -> 7.11

flake.lock, pkgs/osu-lazer-bin/default.nix
=> osu-lazer-bin: 2022.615.0 -> 2022.630.0

flake.lock, pkgs/osu-lazer-bin/default.nix
Tested, seems to work.
Sorry about the merge commit, I'll have to figure out how to make a branch per PR soon.
=> osu-lazer-bin: 2022.630.0 -> 2022.704.0

pkgs/osu-lazer-bin/default.nix
=> osu-lazer-bin: 2022.704.0 -> 2022.709.0

pkgs/osu-lazer-bin/default.nix
=> osu-lazer-bin: 2022.709.0 -> 2022.719.0

pkgs/osu-lazer-bin/default.nix
=> osu-lazer-bin: 2022.719.0 -> 2022.723.0

pkgs/osu-lazer-bin/default.nix
=> osu-lazer-bin: 2022.723.0 -> 2022.731.1

pkgs/default.nix, pkgs/wine/default.nix
=> wine-ge: Proton7-25 -> Proton7-27

pkgs/wine/default.nix
Worth to note, I didn't test anything besides the hashes.
=> wine-{ge,gecko,mono,tkg}: bump {Proton7-29,2.47.3,7.3.0,fix-rev}

pkgs/wine/default.nix
Only tested that it evaluates.
=> wine-{tkg,ge}: bump

pkgs/default.nix, pkgs/dxvk/default.nix, pkgs/vkd3d-proton/default.nix, pkgs/vkd3d-proton/explicitly_define_hex_base.patch, pkgs/wineprefix-preparer/default.nix
Followup to #7
I've tested this with WoW and both d3d11 and d3d12 work. Haven't tested 10/9.
=> dxvk and vkd3d-proton + installer?

pkgs/osu-stable/default.nix
=> bump pkgs.osu-stable sh256 sum

pkgs/osu-stable/default.nix
=> Update pkgs.osu-stable sha256

.github/workflows/update.yml, README.md, pkgs/default.nix, pkgs/faf-client/default.nix, pkgs/faf-client/faf-client-setup.py, pkgs/faf-client/update.sh
The client doesn't even start when not using the latest version. However, I don't want to maintain this package, updating the hash a few times a month. I hope you have some infrastructure ready for updating the hashes, if not, you can use something like [nvfetcher](https://github.com/berberman/nvfetcher) or [nix-update](https://github.com/Mic92/nix-update)
=> Add Forged Alliance Forever

npins/sources.json
=> wine-ge: Proton7-43 -> Proton8-4

npins/sources.json
=> wine-ge: Proton8-4 -> Proton8-6

pkgs/dxvk/default.nix, pkgs/legendary/default.nix, pkgs/osu-stable/default.nix, pkgs/roblox-player/default.nix, pkgs/rocket-league/default.nix, pkgs/vkd3d-proton/default.nix, pkgs/wine-discord-ipc-bridge/default.nix, pkgs/winestreamproxy/default.nix
Removed stuff that `nil` language server told me was useless.
=> treewide: remove unused stuff

.github/workflows/update.yml, npins/sources.json, pkgs/wine/default.nix, pkgs/wine/update-wine-ge.sh
I don't know if this is the right way to do it.
(That is, if the new file is placed where it should be, and whether using `npins add github -b "$latest_branch" "$REPO_OWNER" "$REPO_NAME"` directly in the script is a good way to update wine-ge in `sources.json`.)
(Credits to ChatGPT for the script)
=> wine-ge: add autoupdater

pkgs/osu-lazer-bin/default.nix
this is to avoid [monstrosities like this](https://github.com/chayleaf/dotfiles/blob/ebc7241725e3f40d82e84d213dae0fb3bc1b63ad/home/hosts/nixmsi.nix#L66) (this PR also downgrades dirty hack to just a hack)
=> add command_prefix arg to osu-lazer-bin derivation

.gitignore, pkgs/faf-client/update-src.sh, result
Stop it from creating result symlinks.
=> faf-client: fix update script

pkgs/proton-ge/default.nix
=> proton-ge: 8.6 -> 8.9

pkgs/faf-client/bin.nix, pkgs/faf-client/default.nix, pkgs/faf-client/faf-client-setup.py
also update the setup script (the diff sucks because most of it is just +1 indent) and add myself to maintainers
=> faf-client: fix build

npins/sources.json, pkgs/osu-lazer-bin/info.json
since the update script isn't working, I ran it manually for now
=> osu-lazer-bin: 2023.803.0 -> 2023.812.0

pkgs/star-citizen/default.nix
* Update star-citizen launcher version to version 1.6.8 ([change log](https://robertsspaceindustries.com/spectrum/community/SC/forum/1/thread/rsi-launcher-1-6-8-release-notes))
* Update launch script to update launcher.
=> Update: Update star-citizen 1.6.8

.github/workflows/update-flake.yml, .github/workflows/update.yml
=> CI: fix actions not committing

pkgs/proton-ge/default.nix
- Updated proton-ge from 8.11 to 8.12
- Added an updatescript
- Added preBuild and postBuild hooks
=> proton-ge: 8.11 -> 8.12

pkgs/proton-ge/default.nix
=> proton-ge: 8.12 -> 8.13

pkgs/proton-ge/default.nix
guess what this does (impossible)
=> proton-ge: 8.14 -> 8.15

README.md, pkgs/default.nix, pkgs/titanfall/README.md, pkgs/titanfall/flight-core.nix, pkgs/titanfall/northstar-proton.nix, pkgs/titanfall/viper.nix
- add following titanfall utilities
- viper
- flightcore
- northstarproton
=> add multiple compat tools

pkgs/proton-ge/default.nix
I was going to move this to npins but honestly npins looks like an effing bother
=> proton-ge: 8.15 -> 8.16

.github/workflows/check.yml, pkgs/default.nix, pkgs/modrinth-app/default.nix
=> modrinth-app: init at 0.5.4

README.md
to people like us, the goofy movie is just a movie
=> docs: fix incorrect link destination

pkgs/proton-ge/default.nix
=> proton-ge: 8.16 -> 8.19

pkgs/proton-ge/default.nix
this got out 5 hours after I PR'd the previous one, classic
=> proton-ge: 8.19 -> 8.20

pkgs/proton-ge/default.nix
If this gets another release as I go to bed, I'm going to kill myself
=> proton-ge: 8.20 -> 8.21

flake.nix
I thought this would be very funny. Also helpful, yes.
=> flake: list available modules in throw if default module is used

pkgs/proton-ge/default.nix
=> proton-ge: 8.23 -> 8.24

pkgs/osu-lazer-bin/info.json
=> osu-lazer-bin: 2023.1213.0 -> 2023.1218.0

pkgs/default.nix, pkgs/tmodloader/default.nix
A little hacky, but works. I'll investigate whether or not we can get rid of steam-run in the wrapper in order to slim it down, but dotnet doesn't inspire much confidence.
=> tmodloader: init at 2023.11.3.3

pkgs/star-citizen/README.md, pkgs/star-citizen/default.nix
This PR fixes a typo in the desktop file as well as adds a note for launching control panel which is sometimes needed for using joysticks.
=> Update star-citizen: Fix typo in desktop file and update README

pkgs/star-citizen/default.nix, pkgs/star-citizen/powershell-stub.nix
This adds a needed powershell stub for the electron launcher to create directories.
=> Update star-citizen: include powershell stub

pkgs/wine/supportFlags.nix
Untested.
I only tested it in regular Nixpkgs' Wine.
=> pkgs/wine: enable waylandSupport

pkgs/default.nix, pkgs/mo2installer/default.nix, pkgs/mo2installer/fix.patch, pkgs/mo2installer/steam-redirector.nix
I've added [this](https://github.com/rockerbacon/modorganizer2-linux-installer) script, that allows you to install Mod Organizer 2 for Linux easily.
=> mo2installer: init

pkgs/titanfall/viper.nix
Updates Viper to the latest version.
=> titanfall/viper: update to 1.12.1

pkgs/default.nix
Small pr changing wine version from stable to staging by default for star-citizen.
=> Update star-citizen (wine): stable -> staging

modules/platformOptimizations.nix
Update `platformOptimizations` to match [changes upstream](https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/steamos-customizations-jupiter-20250117.1-1-any.pkg.tar.zst).
Tested on my system to confirm this is working
No maintainers specified, pinging @RTUnreal as they created the module.
=> steam.platformOptimizations: Update steamos customizations

pkgs/star-citizen/default.nix
* Update star-citizen to install the latest launcher version (v2.3.1)
* Ensure that all winetricks are properly installed, including new ones
* Correct installation check to confirm the launcher exists
=> star-citizen: 2.1.0 -> 2.3.1

pkgs/star-citizen/default.nix
* drop unnecessary environment variables
* Move `EOS_USE_ANTICHEATCLIENTNULL` outside of the non-umu block as it is no longer overwritten by umu
* don't remove the EAC files to prevent launch errors
=> star-citizen: Add `--shell` to simplify recreating the environment

pkgs/osu-lazer-bin/default.nix
As commented in https://github.com/fufexan/nix-gaming/pull/264#issuecomment-2972070322
=> osu-lazer-bin: add SDL3 as dependency

npins/sources.json, pkgs/default.nix, pkgs/wine-mono/default.nix, pkgs/wine-mono/info.json, pkgs/wine-mono/update.sh, pkgs/wine/default.nix
=> wine-mono: init and use in wineBuilder

.github/workflows/update.yml, npins/sources.json, pkgs/dxvk/update.sh
=> dxvk: add an update script to fetch dxvk source based on the version of gplasync patch

.github/workflows/build.yml, .github/workflows/update.yml, npins/sources.json, pkgs/default.nix, pkgs/wine/default.nix, pkgs/wine/update-wine-cachyos.sh
`wine-cachyos` is based on proton-wine, with extra CachyOS patches.
@bandithedoge
This PR is based on #288.
=> wine-cachyos: init at 10.0.20250714
