fufexan/nix-gaming

flake.lock, pkgs/wine/default.nix, pkgs/wine/supportFlags.nix
NixOS/nixpkgs#153932 added an additonal argument to the wine base
derivation, controlling which variants of vkd3d are included in the wine
distribution.
This needs to be manually added to 3rd party wine derivations, as there
is no fallback to the previous behaviour.
=> pass vkd3dArches to the wine derivations

flake.lock, pkgs/wine/default.nix
https://github.com/NixOS/nixpkgs/commit/8d65e832f0a18f60e2040940c80d96373ac8b88c has moved all emulators from pkgs/misc/emulators to pkgs/applications/emulators. 
This PR applies that change to nix-gaming.
=> Fix wine derivations with the recent nixpkgs change

.github/workflows/ci.yml, README.md, example.nix, flake.lock, flake.nix, lib/default.nix, pkgs/default.nix, pkgs/legendary/default.nix, pkgs/osu-lazer-bin/default.nix, pkgs/wine/default.nix
I envisioned some kind of function that would take a set of games and declaratively install them, for `legendary`. Currently, there's only `rocket-league` available in this repo, but I wanted to extend the functionality to potentially any game that legendary supports.
The config the user is supposed to write to get the games installed is a bit more verbose than it used to be, but it should make it easier to install games not listed in this repo. I've also tried keeping the options sane and minimal, but there are plenty of options for extending functionality.
Aside from the new `legendaryBuilder`, I've also took the time to apply some stylistic changes to the repo, such as using a single `pkgs` instance for both the builder and the normal `packages`.
Let me know if you have any ideas on …
=> Add legendaryBuilder

pkgs/osu-stable/default.nix
Otherwise we get the following error:
```
error: Package ‘osu-stable’ in /nix/store/nwffh179bzszwry8syj74l4qw6m13aq2-source/pkgs/osu-stable/default.nix:80 has an invalid meta attrset:
- key 'meta.maintainer' is unrecognized; expected one of:
['available', 'badPlatforms', 'branch', 'broken', 'changelog', 'description', 'downloadPage', 'executables', 'homepage', 'hydraPlatforms', 'insecure', 'isBuildPythonPackage', 'isFcitxEngine', 'isGutenprint', 'isHydraChannel', 'isIbusEngine', 'knownVulnerabilities', 'license', 'longDescription', 'mainProgram', 'maintainers', 'maxSilent', 'name', 'outputsToInstall', 'platforms', 'position', 'priority', 'schedulingPriority', 'sourceProvenance', 'tag', 'tests', 'timeout', 'unfree', 'unsupported', 'version'], refusing to evaluate.
```
=> Fix invalid meta

pkgs/osu-stable/default.nix
Peppy updated the `osu!install.exe` file again, thus breaking installing the packages.
This PR updates the `sha256` property in `pkgs/osu-stable/default.nix` to be the latest one.
=> Update pkgs.osu-stable sha256

pkgs/faf-client/default.nix, pkgs/faf-client/update.sh
Now releases will be considered newer than alpha versions for the purposes of automatic update check.
As a bonus, this fixes `jq` having trouble with Github's malformed json API returning unescaped strings.
=> faf-client: sort github releases chronologically

pkgs/osu-lazer-bin/info.json, pkgs/osu-lazer-bin/update.sh
Checks whether the required AppImage exists in the release, otherwise doesn't
update info.json.
Fixes #55
=> osu-lazer-bin: fix update script

pkgs/osu-lazer-bin/default.nix
As the Vulkan (Veldrid) renderer was recently merged into osu!lazer (as broken as it is), to use it we need to add a new dependency for the package. This commit does that.
=> osu-lazer-bin: add vulkan-loader to deps

npins/sources.json, pkgs/wine/default.nix
`wine-ge`: update to Proton7-42
`wine-tkg`: change repo to Kron4ek's for timely updates, and enabled Wayland support for it. Now on Wine 8.5. While Wayland support isn't complete and launching `DISPLAY= winecfg` fails, it doesn't hurt the existing X11 driver.
=> wine-{tkg,ge}: update

pkgs/default.nix, pkgs/wine/default.nix
Example of the issue:
```
$ nix build .\#packages.x86_64-linux.wine-osu --override-input nixpkgs github:NixOS/nixpkgs/nixos-unstable
• Updated input 'nixpkgs':
'github:NixOS/nixpkgs/a1240f6b4a0bcc84fc48008b396a140d9f3638f6' (2023-03-05)
→ 'github:NixOS/nixpkgs/9c8ff8b426a8b07b9e0a131ac3218740dc85ba1e' (2023-04-05)
error: builder for '/nix/store/3fxji15bzc28h8ka1v5b7xa1w5677w2b-wine-osu-7.0.drv' failed with exit code 1;
last 10 log lines:
> tools/install-sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hx32wk55ml88jrb1qxwg5c5yazfm6gf-bash-5.2-p15/bin/sh"
> tools/findfunc: interpreter directive changed from "#!/bin/sh" to "/nix/store/0hx32wk55ml88jrb1qxwg5c5yazfm6gf-bash-5.2-p15/bin/sh"
> tools/config.sub: interpreter directive changed from "#! /bin/sh" to …
```
=> wine-osu: fix build with recent commits of nixpkgs-unstable

flake.lock, npins/sources.json
Also update flake.lock.
Currently, the game I was playing (Rise of the Tomb Raider) doesn't launch after I updated NixOS. With this, it launches again.
=>  wine-ge: Proton7-42 -> Proton7-43

.github/workflows/ci.yml, README.md, npins/default.nix, pkgs/default.nix, pkgs/proton-ge/default.nix
Simply adds the proton-ge derivation to nix-gaming flake's outputs, I was getting tired of maintaining in my own flake.
[This issue](https://github.com/NixOS/nixpkgs/issues/73323#issuecomment-1079939987) provides instructions on how the user may use the proton-ge derivation on primarily NixOS systems. I assume it would be similar on extending PATH on non-nixos, or linking imperatively.
=> add proton-ge derivation

README.md, pkgs/faf-client/README.md, pkgs/osu-lazer-bin/README.md, pkgs/osu-stable/README.md, pkgs/proton-ge/README.md, pkgs/technic-launcher/README.md, pkgs/wine-discord-ipc-bridge/README.md, pkgs/wine/README.md, pkgs/winestreamproxy/README.md
Declutters the main README while keeping info within reach.
=> treewide: split README into each package

example.nix, flake.lock, flake.nix, lib/default.nix, pkgs/default.nix, pkgs/wine/default.nix
Not a necessary feature but it is easier to integrate into a framework used by
many.
legendary-builder: simplify by making it a function
NOTICE: now legendary-builder requires a `pkgs` argument, and no longer depends
on a `system` key being present!
=> flake: use flake-parts

pkgs/default.nix, pkgs/osu-lazer-bin/default.nix, pkgs/osu-mime/default.nix, pkgs/osu-stable/default.nix
Adds [MIME type information](https://specifications.freedesktop.org/shared-mime-info-spec/shared-mime-info-spec-0.21.html#idm46148007863824) and icons for file types used by osu! and makes the desktop files of `osu-lazer-bin` and `osu-stable` handle them. This allows, for example, double clicking on an `.osz` file in a file manager to automatically launch `osu-lazer-bin` or `osu-stable` and have them import the beatmap archive. The desktop files will now also handle `osu://` URLs (which can be tested using `xdg-open <url>` or a similar tool; the URL schema can be found at the bottom of [this page](https://github.com/ppy/osu-api/wiki#reference)).
The MIME type information and icons are contained in a new `osu-mime` package, which is added to `osu-lazer-bin` and `osu-stable`'s …
=> osu-lazer-bin, osu-stable: handle MIME types

README.md
Per [RFC 45](https://github.com/NixOS/rfcs/blob/master/rfcs/0045-deprecate-url-syntax.md), URL literals are deprecated. Strings should be used instead. No URL literals are used in this flake, but the readme still recommends deprecated syntax.
=> README.md: remove deprecated url syntax

npins/sources.json, pkgs/wine/update-wine-ge.sh
* Update `pkgs/wine/update-wine-ge.sh` to exclude game specific versions
* Update `npins/sources.json` to correct to the most up to date proton version
Fixes #94.
=> Fix: npins wrongly selecting game-specific proton versions

pkgs/wine-discord-ipc-bridge/README.md, pkgs/wine-discord-ipc-bridge/default.nix
to use, check ``whereis winediscordipcbridge-steam.sh`` and add ``/bin/winediscordipcbridge-steam.sh %command%`` in the launch options there might be a better way, but im not sure.
fixes #96
=> wine-discord-ipc-bridge: add steam bridge

pkgs/star-citizen/default.nix
- Launcher is able to update itself
- No longer sets default DXVK_HUD variables
Should fix issues in #122
Confirmed launcher runs, unable to test game but changes should  not effect the game itself.
=> Update: Star Citizen

pkgs/star-citizen/default.nix
- Updated Star Citizen
- Removed uneeded environment variables
=> Update Star-Citizen: 1.6.9 -> 1.6.10

pkgs/proton-ge/default.nix
- **proton-ge: 8.31 -> 8.32**
- Uses stdenvNoCC instead of stdenv, since we don't need a compiler for unarchiving a tar.
=> proton-ge: 8.31 -> 8.32

pkgs/star-citizen/README.md, pkgs/star-citizen/default.nix
- Add `wineDllOverrides` to attributes to allow overriding
- Add `EOS_USE_ANTICHEATCLIENTNULL` (patch included in Proton)
=> Update star-citizen to allow additional DLL Overrides

pkgs/proton-ge/default.nix
Bump version to latest GE-Proton release.
Also updated hash to sha512 as that is what is provided from the release page
=> Update to GE-Proton9-1

README.md, modules/default.nix, modules/platformOptimizations.nix, modules/steamosSysctls.nix
These settings are taken from the [`steamos-customizations-jupiter`](https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/steamos-customizations-jupiter-20230911.1-1-any.pkg.tar.zst) package on SteamOS.
=> modules: add platformOptimizations

pkgs/star-citizen/default.nix
* Removes uneeded winetricks
* Remove uneeded DLL OVerrides
* Update environment variables to include ones in the lutris install script
* Add option enableGlCache per nvidia driver docs, this is on by default
* Add option glCacheSize default is the standard size of 1073741824
=> Update star-citizen: include changes made in lutris install script

pkgs/osu-stable/default.nix
Details on the fix can be found on [ThePooN's discord server](https://discord.com/channels/209933203782369281/1225791538366386326/1225791539717079124).
This does not fix prefixes created before the patch, to do that you have to run `winetricks -q dotnet45` within the existing osu prefix.
Fixes: #174
=> osu-stable: fix connection issues in installer and client

pkgs/default.nix, pkgs/rocket-league/bakkesmod.nix, pkgs/rocket-league/default.nix
Bakkesmod is a very popular mod for Rocket League, it lets you practice more effectively, allows you to change car decals, and lets you install and run extra mods.
I added bakkesmod alongside `nix-gaming#rocket-league` to my config a while ago and using it without issues for some time, I believe other `nix-gaming` users might benefit from it as well hence I am creating this PR.
My nix skills are not so advanced, so if you see possible improvements, feel free to improve them. For example, both the newly added `bakkesmod.nix` file and previously existing `rocket-league/default.nix` file share some parameters such as location and wine, ideally they should be the same, but since they are in different files I am not sure how I could achieve that. Maybe it makes sense to just add another …
=> add bakkesmod for rocket league

.github/workflows/build.yml, flake.lock, flake.nix, pkgs/default.nix, pkgs/star-citizen/README.md, pkgs/star-citizen/default.nix
This is draft PR for migrating to umu at least for star-citizen to resolve #151 
Currently doesn't run (but does build) due to how umu is packaged in their flake
Star Citizen Updates:
• Add attr "useUmu" to support umu:
• Add attr protonPath to set umu's proton version:
This defaults to proton-ge-bin in nixpkgs. To always use the latest
proton-ge you can set this to "GE-Proton"
• Add attr protonVerbs to set proton verbs, only affects umu
Flake lock file updates:
• Updated input 'nixpkgs':
'github:NixOS/nixpkgs/02923630b89aa1ab36ef8e422501a6f4fd4b2016?narHash=sha256-OhysviwHQz4p2HZL4g7XGMLoUbWMjkMr/ogaR3VUYNA%3D' (2024-05-18)
→ 'github:NixOS/nixpkgs/9355fa86e6f27422963132c2c9aeedb0fb963d93?narHash=sha256-%2B%2BTYlGMAJM1Q%2B0nMVaWBSEvEUjRs7ZGiNQOpqbQApCU%3D' (2024-07-16)
• Added input …
=> Update Star Citizen: Add UmU

npins/sources.json, pkgs/default.nix, pkgs/winetricks-git/default.nix
Initialize winetricks-git at the latest git rev
=> init: winetricks-git rev72b934e1e10c041ec6986f5f2fb4f143d8f6b941

pkgs/osu-lazer-bin/default.nix
With recent update shenanigans occuring with upstream and Velopack on Linux recently, and due to how Nix works, it's preffered to disable auto-updating.
This is already done on the nixpkgs derivation.
=> osu-lazer-bin: ensure that Velopack is disabled

pkgs/star-citizen/default.nix
* Bump launcher version to 2.1.0
* Add work around for java script error 
fixes #206
=> Update star-citizen: 2.0.5 -> 2.1.0

pkgs/osu-lazer-bin/default.nix
It seems osu-lazer's icon has been renamed in the last update, breaking the build process.
This fixes #224
=> osu-lazer-bin: fix build failure due to missing icon

.github/workflows/build.yml, flake.lock, flake.nix, npins/sources.json, pkgs/default.nix, pkgs/osu-stable/default.nix, pkgs/star-citizen/default.nix
This pull request resolves issue #204. Following the upstream renaming of `umu` to `umu-launcher`, I have updated the name accordingly. If you prefer this change to be implemented as a soft change for now, please let me know.
Mentioning @ProspectPyxis since this also changes `osu-stable`. I did a quick test to ensure it's working.
=> umu -> umu-launcher: switch to npins & rename to umu-launcher

pkgs/star-citizen/default.nix
CIG has since fixed EAC, and it now works correctly under linux. More so, it is actually required for playing star citizen 4.0.
This PR adds a `disableEac` flag to make the disabling optional; some fixes to make it work; as well as making EAC be enabled by default.
=> star-citizen: add support for EAC

npins/sources.json, pkgs/default.nix, pkgs/dxvk-nvapi/default.nix
Initial PR to add dxvk-nvapi currently doesn't include vulkan layer for NVIDIA reflex.
=> dxvk-nvapi: init at 0.9.0

pkgs/default.nix, pkgs/dxvk-nvapi/vkreflex-layer.nix
I didn't use the vulkan-headers from nixpkgs because the version is too new for vkroots.
The compatibility layer appears correctly in vulkaninfo, but no further testing has been done yet.
@LovingMelody
=> dxvk-nvapi-vkreflex-layer: init at 0.9.0

pkgs/dxvk-nvapi/default.nix
PR to have dxvk-nvapi to use headers included in the repo instead of nixpkgs as nixpkgs is too new.
=> dxvk-nvapi: Use headers included in the repo

npins/sources.json, pkgs/dxvk/default.nix, pkgs/vkd3d-proton/default.nix, pkgs/wineprefix-preparer/default.nix
Fixes #85
Closes #126
This gets them working again but isn't using npins any more.
=> dxvk,vkd3d-proton: fix build, update, swap to dxvk-gplasync

pkgs/vkd3d-proton/default.nix, pkgs/vkd3d-proton/explicitly_define_hex_base.patch
Previously version/build were set incorrectly as there's no .git available with nix
=> vkd3d-proton: use correct version info from pin metadata

.github/workflows/build.yml, pkgs/default.nix, pkgs/wineprefix-preparer/default.nix
Adding dxvk-nvapi to wineprefix-preparer.
Copying the star-citizen derivation, we install both DLLs in both locations; nvapi has a unique name per arch.  
https://github.com/fufexan/nix-gaming/blob/29ba418c6449f123b0d4319d4226e06bd2038150/pkgs/star-citizen/default.nix#L105-L108
nvapi DLLs will do nothing unless DXVK_ENABLE_NVAPI=1 is set at use time; should be safe to install unconditionally.
=> wineprefix-preparer: add nvapi, add to build matrix

pkgs/default.nix, pkgs/star-citizen/default.nix
* `use wineprefix-preparer`
* only run gamemode if it is already present on the system
gamemode isnt always needed and would already be present
if it is configured correctly due to polkit rules
* Update RSI launcher from 2.3.1 to 2.3.2
=> star-citizen: 2.3.1 -> 2.3.2

pkgs/faf-client/default.nix, pkgs/faf-client/ice-adapter.nix
Fix #253.
According to [this](https://github.com/NixOS/nixpkgs/blob/218a02803ba5d26453f94559895f3d1b90705976/pkgs/development/tools/build-managers/gradle/update-deps.nix#L134), bwrap is not necessary for update scripts, so I simply turned it off.
=> faf-client: disable bwrap for update script

pkgs/osu-lazer-bin/default.nix
As noted by @smoogipoo in https://github.com/fufexan/nix-gaming/pull/264#issuecomment-2982888746, we've been replacing the AppImage's libraries with our own, even though osu! intentionally statically-links needed libraries with specific patches.
This PR also removes unused flags such as `COMPlus_GCGen0MaxBudget` which have been removed.
Requires testing.
=> osu-lazer-bin: clean up derivation, don't replace libraries

pkgs/default.nix, pkgs/wine/default.nix
Build time can be reduced since we no longer need to build compilers ourselves.
=> wine-tkg{,ntsync}: build with default gcc

pkgs/dxvk/default.nix
Fixes #276
Commit description:
> DXVK's meson.build now has options for enabling specific DXVK Native backends (SDL2, SDL3, GLFW), so the package's arguments are updated to reflect that.
> 
> `enableParallelBuilding` is removed since it is already set by the Meson setup hook in nixpkgs.
SDL3 seemed like the most reasonable backend to enable by default.
=> dxvk: adapt for 2.7

.github/workflows/build.yml, npins/sources.json, pkgs/default.nix, pkgs/wine/default.nix, pkgs/wine/update-wine-tkg.sh
[NTSync has been upstreamed into Wine](https://www.winehq.org/news/2025100301), meaning that regular `wine-tkg` also includes it.
In fact, [the NTSync branch of Kron4ek](https://github.com/Kron4ek/wine-tkg/tree/ntsync) has not been updated.
Tested that `wine-tkg` does indeed use NTSync (through MangoHud).
=> wine-tkg-ntsync: remove
